### ISSUE TITLE
I can’t get the plugin to load though (see screenshot).

### ISSUE THREAD

**Issue by tobiashochguertel** [tobiashochguertel/c4-draw.io#1]
Oh cool, that looks useful! I can’t get the plugin to load though (see screenshot).

![din2ixdxgaanow8](https://user-images.githubusercontent.com/3332669/29753289-a54d1358-8b6e-11e7-8360-48b73df467a1.png)

Reported by: https://twitter.com/simonbrown/status/901694241587519488

**Comment by tobiashochguertel** [comment]
It works in Safari (just not Chrome). :-)

![din4yylxgaabe5z](https://user-images.githubusercontent.com/3332669/29753309-07198f94-8b6f-11e7-89d9-da01ef98fc0d.png)

**Comment by wimdeblauwe** [comment]
I can confirm it works with Safari, but does not work with Chrome.

**Comment by tobiashochguertel** [comment]
@wimdeblauwe okay, I can provide currently only the solution to open draw.io with "https=0" e.g. http://www.draw.io/?splash=0&https=0 and to provide the 'c4.js' from localhost e.g. 
![image](https://user-images.githubusercontent.com/3332669/30016580-03dce19a-9156-11e7-84e7-0ab5053a811d.png)

To get a quick http server you can use `npm install -g http-server` and run it from your working copy of this repository: `http-server`

```
0 hochguertelto@Tobiass-MBP:~/Projekte/03_other/c4-draw.io/Users/hochguertelto/Projekte/03_other/c4-draw.io (master=)
$ http-server
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://192.168.0.189:8080
  http://172.16.48.1:8080
  http://172.16.194.1:8080
Hit CTRL-C to stop the server
```

But may be it run's in chrome only by setting 'https=0' Parameter in the url?

I have not had the time yet to continue the work on the plugin and to check what is the reason for this bug - may be it is possible to serv the c4.js file via github pages instead of github-raw file access. I plan to continue the work in this week.

I hope this helps?

**Comment by tobiashochguertel** [comment]
@wimdeblauwe I have created the github pages, I think this is the best solution: https://tobiashochguertel.github.io/c4-draw.io/c4.js

I have quick check this and it works for me, but can you give this a try?

**Comment by wimdeblauwe** [comment]
I can confirm it works by just using https://tobiashochguertel.github.io/c4-draw.io/c4.js as plugin url. Thx!

**Comment by tobiashochguertel** [comment]
@wimdeblauwe thanks for the Feedback. I changed the Link in the Readme.md file. I think this was not really a software bug - more an thing that I have used raw.github.com as an CDI which it isn't.  I close this bug issue now.
