### ISSUE TITLE
Problems with collaborative editing in draw.io

### ISSUE THREAD

**Issue by alderg** [tobiashochguertel/c4-draw.io#11]
We're seeing problems in our app when used with this plugin and collaborative editing, which was recently added for OneDrive and Google Drive, but also for GitHub and Device files (via File, Synchronize). The problem seems to be related to the plugin attaching data to cells outside of the cell.value property. The recommended and supported custom data storage in cells is inside an XML node in cell.value (see Edit, Edit Data). HTH

**Comment by spokeo-james** [comment]
Want to confirm that we're having issues importing documents that were saved to xml with these elements. When imported, they give an "Illegal constructor" error if the plugin isn't loaded.
