### ISSUE TITLE
Since latest release v11.1.1 is not able to use C4 model shapes

### ISSUE THREAD

**Issue by alnavart** [tobiashochguertel/c4-draw.io#14]
Hi,

I can open the diagrams, but is not possible to copy/paste or add new C4 shapes. When copy, shows a dialog with Error "Illegal constructor"

I tried to install again the plugin, draw doesn´t show any error, but it doesn´t add the new shapes section.

If I can provide you more info don't hesitate to contact me.

Release notes:
https://github.com/jgraph/drawio-desktop/releases/tag/v11.1.1

Thanks

**Comment by alnavart** [comment]
Seems there aren´t a problem with the plugin, only is because now not supports external plugins in desktop version for security reasons https://github.com/jgraph/drawio-desktop/issues/139

Sorry, thanks

**Comment by benoit-romito** [comment]
Hi, is there any alternatives at the moment ?

**Comment by alnavart** [comment]
Sorry, I missed to answer you, using the online editor, draw.io allows to load the plugin. At the moment is how I'm working. Thanks

**Comment by alnavart** [comment]
Also, today I tested a solution provided in the draw.io thead, based on download and use local references and works fine:

For macOS desktop:
1、Download plugin file. eg: /Users/xxx/plugins/c4.js
2、Add plugin in Plugin Panel
URL: file:///Users/xxx/plugins/c4.js
3、Apply and restart.

**Comment by benoit-romito** [comment]
It works like a charm ! Thank you for your feedback, it is much appreciated 👍

**Comment by chipbite** [comment]
Hello from 2021... 👋 
I tried local file for app.diagrams.net and I get an error trying to load the local plugin...
![image](https://user-images.githubusercontent.com/559199/116140031-03fca300-a6d7-11eb-8a81-1673fe784e7a.png)

So I suspect this does not work anymore.
