### ISSUE TITLE
How to setup this plugin to work in Desktop version of draw.io?

### ISSUE THREAD

**Issue by Zaijo** [tobiashochguertel/c4-draw.io#8]
Hello, I downloaded a diagram created online on draw.io using your plugin (it worked great) and then I installed desktop version of Draw.io, which doesn't offer the `Extras -> Plugins` menu.

Everything look fine, but I can't create any more of your predefined shapes.

Any ideas?

BTW, good work.

**Comment by Zaijo** [comment]
I opened an issue on draw.io desktop version itself. https://github.com/jgraph/drawio-desktop/issues/7

**Comment by tobiashochguertel** [comment]
Hello @Zaijo,

at the moment I have no idea. I'm not sure if it is possible when you compile and build your own standalone desktop version which has a copy of the c4 plugin in the source code.

Thank you for the praise. : )

// Offtopic, in the future we will integrate it into the core... 
The draw.io team asked me on twitter if they could integrate this plugin into the core, when it's done. https://twitter.com/drawio/status/901699014474772480
But its not yet done.

Kind regards,
Tobias

**Comment by lzrski** [comment]
Hey! Just wanted to say thank you for Draw.io and that having plugins in Electron app would be very cool.

We are using Draw.io for diagramming database schema (using SQL plugin) and keep diagrams in Git repository (as SVG+XML). GitHub integration works, but only for GitHub, is a little bit cumbersome and requires extensive permissions. Working with a desktop app and local filesystem would be preferable for us.

I understand that this may be technically challenging and not at the top of your priority list. If there is any workaround (maybe building from sources with plugin?) I would greatly appreciate hints.

**Comment by tad-lispy** [comment]
Ugh, just realized I was commenting in a wrong repo. Sorry :-P

**Comment by MareGeldenhuys** [comment]
The latest desktop version of Draw.io includes the plugin functionality. You should be able to close this issue now.

**Comment by Zaijo** [comment]
It works now :) Thanks for information.
